# Generated by Django 6.0 on 2026-01-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('ABOUT', 'About'), ('SKILLS', 'Skills'), ('LINKS', 'Links'), ('PROJECT', 'Projects'), ('EXPERIENCE', 'Experience')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('is_enable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('profile', 'section_type')},
            },
        ),
    ]
