# Generated by Django 6.0 on 2026-01-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesection',
            name='section_type',
            field=models.CharField(choices=[('ABOUT', 'About'), ('SKILLS', 'Skills'), ('LINKS', 'Links'), ('PROJECTS', 'Projects'), ('EXPERIENCE', 'Experience')], max_length=20),
        ),
    ]
