# Generated by Django 6.0 on 2026-01-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profilesection_section_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesection',
            old_name='is_enable',
            new_name='is_enabled',
        ),
    ]
