# Generated by Django 6.0 on 2026-01-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilesection',
            unique_together=set(),
        ),
    ]
