# Generated by Django 4.2.23 on 2026-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profilesection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesection',
            name='section_type',
            field=models.CharField(choices=[('ABOUT', 'About Me'), ('SKILLS', 'Skills'), ('LINKS', 'Links'), ('PROJECTS', 'Projects'), ('EXPERIENCE', 'Experience'), ('PERSONAL', 'Personal Details'), ('CUSTOM', 'Custom Section')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='profilesection',
            constraint=models.UniqueConstraint(condition=models.Q(('section_type', 'ABOUT')), fields=('profile', 'section_type'), name='unique_about_section'),
        ),
        migrations.AddConstraint(
            model_name='profilesection',
            constraint=models.UniqueConstraint(condition=models.Q(('section_type', 'PERSONAL')), fields=('profile', 'section_type'), name='unique_personal_section'),
        ),
    ]
