# Generated by Django 6.0 on 2026-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('FREE', 'Free Plan'), ('MONTHLY', 'Pro Monthly'), ('YEARLY', 'Pro Yearly')], default='FREE', max_length=20, null=True),
        ),
    ]
