# Generated by Django 6.0 on 2026-01-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_subscription_plan_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='payment_id',
        ),
    ]
