# Generated by Django 6.0 on 2026-01-29 06:50

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('THEME UPDATE', 'Theme Update'), ('GENERAL UPDATE', 'General Update'), ('TUTORIAL', 'Tutorial')], max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('sub_desc', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blogs_thumbnail')),
            ],
        ),
    ]
