# Generated by Django 6.0 on 2026-01-29 06:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a Image (max 4MB)', null=True, upload_to='profile_images/', validators=[accounts.models.validate_image_size]),
        ),
    ]
