# Generated by Django 6.0 on 2026-01-20 06:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username_alter_userdetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a Image (max 5MB)', null=True, upload_to='profile_images/', validators=[accounts.models.validate_image_size]),
        ),
    ]
